AppBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        token:
            type: string
            length: 255
            nullable: true
            unique: true
        created:
            type: datetime
        modified:
            type: datetime
    lifecycleCallbacks: {  }
